///////////////////////////////////////////////////////////////////////
// Optional component that deals with Imoen learning magic with Liia //
// Just pseudo training for now                                      //
// Allows for training to be postponed to the start of SoD           //
///////////////////////////////////////////////////////////////////////

DEFINE_ACTION_FUNCTION liia BEGIN
	EXTEND_TOP ~BG0125.BCS~ ~%mod_root%/scripts/bg0125_liia.baf~
END
