/////////////////////////////////////////////////////////////////////////////////
// Optional component that adds bounty quests for all of Sarevok's supporters  //
// This option has Sarevok's survivors flee upon his death to give more quests //
// And includes a gentler version of the Tamoko bounty quest                   //
/////////////////////////////////////////////////////////////////////////////////

DEFINE_ACTION_FUNCTION quests2 BEGIN
	INCLUDE ~%mod_root%/components/quests_common.tpa~
	INCLUDE ~%mod_root%/components/survivors_flee.tpa~
END