///////////////////////////////////////
// Component that skips sailing time //
///////////////////////////////////////

DEFINE_ACTION_FUNCTION timers_skip_sail BEGIN
	COPY_EXISTING ~ISLON.bcs~ ~override~
   		DECOMPILE_AND_PATCH BEGIN
      		REPLACE_TEXTUALLY ~AdvanceTime(TWENTYFIVE_DAYS)~ ~~
   		END
	BUT_ONLY_IF_IT_CHANGES

	COPY_EXISTING ~ISLOFF.bcs~ ~override~
   		DECOMPILE_AND_PATCH BEGIN
      		REPLACE_TEXTUALLY ~AdvanceTime(TWENTYTWO_DAYS)~ ~~
   		END
	BUT_ONLY_IF_IT_CHANGES
END