///////////////////////////////////////////////////////////////////////////////////////////////
// Block added to canned NPC scripts if staying or leaving after Korlasz is up to the player //
// If no corresponding dialogue is found, default is for the NPC to stay                     //
// Compiled via main_common.tpa                                                              //
///////////////////////////////////////////////////////////////////////////////////////////////

IF
	Global("#L_PlayersChoiceAfterKorlasz","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("#L_PlayersChoiceAfterKorlasz","LOCALS",1)
		Continue()
END
