////////////////////////////////////////////////////////////////
// World event timers begin at the moment of Sarevok's death  //
// Patched via timers_common.tpa                              //
////////////////////////////////////////////////////////////////
IF
	Dead("Sarevok")
	Global("#L_TimersSet","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("#L_TimersSet","MYAREA",1)
		SetGlobalTimer("#L_NextWaveTimer","GLOBAL",SEVEN_DAYS)	// 1st wave of refugees
  		Continue()
END	

